module.exports = {
  GROUP: {
    ACTIVE: 'GROUP_ACTIVE',
    INACTIVE: 'GROUP_INACTIVE'
  },
  PERMISSION: {
    RECEIVED_APPLICATION: 'PERMISSION_RECEIVED_APPLICATION',
    REJECTED_APPLICATION: 'PERMISSION_REJECTED_APPLICATION',
    REVOKED_APPLICATION: 'PERMISSION_REVOKED_APPLICATION',
    BANNED: 'PERMISSION_BANNED',
    UNBANNED: 'PERMISSION_UNBANNED',
    GRANTED_MEMBER: 'PERMISSION_GRANTED_MEMBER',
    REVOKED_MEMBER: 'PERMISSION_REVOKED_MEMBER',
    GRANTED_ADMIN: 'PERMISSION_GRANTED_ADMIN',
    REVOKED_ADMIN: 'PERMISSION_REVOKED_ADMIN'
  },
  OFFER: {
    EXPIRED: 'OFFER_EXPIRED',
    ENDED: 'OFFER_ENDED',
    FEEDBACK: 'OFFER_FEEDBACK'
  },
  PROPOSAL: {
    RECEIVED: 'PROPOSAL_RECEIVED',
    ACCEPTED: 'PROPOSAL_ACCEPTED',
    REJECTED: 'PROPOSAL_REJECTED',
    FEEDBACK: 'PROPOSAL_FEEDBACK'
  },
  VOUCH: {
    RECEIVED: 'VOUCH_RECEIVED',
    ACCEPTED: 'VOUCH_ACCEPTED',
    REJECTED: 'VOUCH_REJECTED'
  },
  MESSAGE: {
    PRIVATE_RECEIVED: 'PRIVATE_RECEIVED'
  }
};
